name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - main  # Change this to the default branch of your repository (e.g., master or main)
  pull_request:
    branches:
      - main  # Optional: deploy when a PR is made to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Pandoc and LibGLU
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc
        sudo apt-get install -y libglu1-mesa libxi6 libxrender1
        sudo apt-get install -y python3-pyqt5

    - name: Install Qt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libegl1 \
          libgl1 \
          libxkbcommon-x11-0 \
          libxcb-cursor0 \
          libxcb-xinerama0 \
          libxcb-icccm4 \
          libxcb-image0 \
          libxcb-keysyms1 \
          libxcb-randr0 \
          libxcb-render-util0 \
          libxcb-shape0 \
          libxcb-sync1 \
          libxcb-xfixes0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e . 
        pip install sphinx sphinx_rtd_theme nbsphinx

    - name: Build the documentation
      run: |
        sphinx-build -b html doc-sphinx/source doc-sphinx/_build/html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: doc-sphinx/_build/html  # Path to your built HTML docs
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Token provided automatically by GitHub
        publish_branch: gh-pages  # The branch that will host your docs
