name: SQDMetal Test Workflow

on: [pull_request, push, workflow_dispatch]

jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest]

    # XXX Workaround for Windows runners redirecting the output of commands to files.
    # See: https://github.com/databrickslabs/dbx/issues/455#issuecomment-1312770919
    env:
      PYTHONIOENCODING: "utf8"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"   # Ensure the latest version is installed
          auto-activate-base: true      # Automatically activate base environment
          activate-environment: false  # Don't activate environment yet
          
      - name: Initialize Conda for PowerShell (if using pwsh)
        run: |
          powershell -command "Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser"
          # conda init
          # Verify conda is available and initialized
          conda --version

      - name: Create environment from yml
        run: |
          # conda activate base      # Activate base environment
          conda init powershell
          conda env create -n sqdmetal_env -f env_windows.yml  # Create environment
          # conda create -n sqdmetal_env python=3.11  # Force Python 3.10
          conda info --envs
          # conda env update -n sqdmetal_env --file env_windows.yml
          # conda activate sqdmetal_env  # Activate the environment

      - name: Install the package in editable mode
        run: |
          powershell -command "Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser"
          powershell -command "C:/Miniconda3/envs/sqdmetal_env/python.exe -m pip install -e ."

      # - name: Pre-build Matplotlib font cache
      #   run: C:/Miniconda3/envs/sqdmetal_env/python.exe -c "import matplotlib.pyplot as plt; plt.figure()"

      # - name: Run tests
      #   run: |
      #     powershell -command "C:/Miniconda3/envs/sqdmetal_env/python.exe UnitTests/testBasicQiskitMetal.py"
          
      - name: Run unittest tests
        run: powershell -command "C:/Miniconda3/envs/sqdmetal_env/python.exe -m unittest discover -s UnitTests"
