name: SQDMetal Test Workflow

on: [pull_request, push, workflow_dispatch]

jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"   # Ensure the latest version is installed
          auto-activate-base: true      # Automatically activate base environment
          activate-environment: false  # Don't activate environment yet
          
      - name: Initialize Conda for PowerShell (if using pwsh)
        run: |
          # conda init
          # Verify conda is available and initialized
          conda --version

      - name: Create environment from yml and activate
        run: |
          # conda activate base      # Activate base environment
          conda env create -n sqdmetal_env -f env_windows.yml  # Create environment
          "$CONDA/bin/activate" sqdmetal_env  # Activate the environment

      - name: Install the package in editable mode
        run: |
          pip install -e .

      - name: Pre-build Matplotlib font cache
        run: python -c "import matplotlib.pyplot as plt; plt.figure()"

      - name: Run tests
        run: |
          python UnitTests/testBasicQiskitMetal.py
          
      - name: Run unittest tests
        run: python -m unittest discover -s UnitTests
